services:
  - name: frontend
    type: web
    buildCommand: npm install && npm run build
    startCommand: node App.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - name: backend
    type: web
    buildCommand: pip3 install -r requirements.txt
    # startCommand: python3 script.py
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
